version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: koperasi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koperasi_umb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - koperasi_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koperasi_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/koperasi_umb
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - koperasi_network

networks:
  koperasi_network:
    driver: bridge

volumes:
  postgres_data: