-- AlterTable
ALTER TABLE `categories` MODIFY `icon` VARCHAR(191) NULL DEFAULT '📦';

-- AlterTable
ALTER TABLE `products` MODIFY `ownershipType` ENUM('TOKO', 'TITIPAN', 'SUPPLIER') NOT NULL DEFAULT 'TOKO';

-- AlterTable
ALTER TABLE `stock_movements` MODIFY `movementType` ENUM('PURCHASE_IN', 'CONSIGNMENT_IN', 'CONSIGNMENT_RETURN', 'SALE_OUT', 'RETURN_IN', 'RETURN_OUT', 'EXPIRED_OUT', 'ADJUSTMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'RESTOCK') NOT NULL,
    MODIFY `referenceType` ENUM('PURCHASE', 'CONSIGNMENT_BATCH', 'SALE', 'ADJUSTMENT', 'EXPIRY', 'STOCK_REQUEST') NULL;
